### ISSUE TITLE
Move react and react-dom to peer dependencies

### ISSUE THREAD

**Issue by zakangelle** [angelle-sw/use-fetch-hooks#12]
Since this is a library intended to be used in React apps, we should express our react dependencies as peer dependencies and enforce a post-hooks release version.

```
"peerDependencies": {
  "react": ">=16.8.0",
  "react-dom": ">=16.8.0"
}
```

**Comment by jpangelle** [comment]
Closed with this [commit](https://github.com/angelle-sw/use-fetch-hooks/commit/76ae9a97a228ba380871a71e800a6e538c15b4f9)
