### ISSUE TITLE
Use react-hooks-testing-library

### ISSUE THREAD

**Issue by zakangelle** [angelle-sw/use-fetch-hooks#3]
Use [react-hooks-testing-library](https://github.com/testing-library/react-hooks-testing-library) to test hooks business logic.

**Comment by jpangelle** [comment]
Will do

**Comment by jpangelle** [comment]
Closed via this [commit](https://github.com/angelle-sw/use-fetch-hooks/commit/b7cfd490bc66748691098584be4b914762dbb350)
